### ISSUE TITLE
Mina Draft Document

### ISSUE THREAD

**Issue by nkaskov** [NilFoundation/evm-mina-verification#13]
- https://hackmd.io/u_2Ygx8XS5Ss1aObgOFjkA?view#Definitions
- https://www.youtube.com/watch?v=ZQkzTB8VDzs

**Comment by SK0M0R0H** [comment]
https://o1-labs.github.io/mina-book/crypto/overview.html
https://github.com/MinaProtocol/mina/blob/feature/8407-spec-ouroboros-samasika-consensus/docs/specs/consensus/README.md
