### ISSUE TITLE
Implement PLONK syntax support

### ISSUE THREAD

**Issue by nkaskov** [NilFoundation/evm-mina-verification#2]
Duplicates corresponding [issue](https://github.com/NilFoundation/crypto3-blueprint/issues/16) in Blueprint circuit repository.

**Comment by nemothenoone** [comment]
Done with https://github.com/NilFoundation/crypto3-blueprint/pull/25/commits/39cee7ee80e0bf8d0fa9595a04cc59b0a007bca1
