### ISSUE TITLE
Implement assembly-based backend

### ISSUE THREAD

**Issue by nkaskov** [NilFoundation/evm-mina-verification#6]
Duplicates corresponding [issue](https://github.com/NilFoundation/crypto3-multiprecision/issues/18) in Multiprecision repository.

**Comment by nemothenoone** [comment]
Done with [c432b5a](https://github.com/NilFoundation/crypto3-multiprecision/commit/c432b5a3dd043afe0b9a2e2f3b4867343bad0f92).
